/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseTaskResponse } from '../../models/page-response-task-response';

export interface FindTasksByDueDate$Params {
  page?: number;
  size?: number;
  DueDate: string;
}

export function findTasksByDueDate(http: HttpClient, rootUrl: string, params: FindTasksByDueDate$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTaskResponse>> {
  const rb = new RequestBuilder(rootUrl, findTasksByDueDate.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.path('DueDate', params.DueDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseTaskResponse>;
    })
  );
}

findTasksByDueDate.PATH = '/tasks/DueDate/{DueDate}';
