/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  createdAt: string;
  id?: number;
  message: string;
  status?: 'READ' | 'UNREAD';
}
