/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskRequest {
  category: string;
  description: string;
  dueDate: string;
  id?: number;
  importance: 'HIGH' | 'MEDIUM' | 'LOW';
  status: string;
  title: string;
}
